@startuml
(*) --> "Нажатие кнопки 'Login'"
--> "Ввод данных"
if "Пользователь ввел данные" then
  --> [Данные введены] "Система проверяет корректность данных"
  if "Данные корректны" then
    --> [Данные корректны] "Перенаправление на главную страницу"
    --> "Завершение авторизации"
  else
    --> [Данные не корректны] "Система отображает сообщение об ошибке"
    --> "Вывод сообщения об ошибке"
  endif
else
  --> [Данные не введены] "Система отображает сообщение об ошибке"
  --> "Вывод сообщения об ошибке"
endif
@enduml