@startuml
(*) --> "Пользователь выбирает продукт"

if "Продукт выбран" then
  --> "Система отображает информацию о продукте"
  --> "Пользователь решает купить продукт"

  if "Пользователь решает купить" then
    --> "Система запрашивает данные для оплаты"

    if "Данные введены" then
      --> "Система обрабатывает платеж"

      if "Платеж успешен" then
        --> "Система регистрирует покупку"
        --> "Пользователю отображается подтверждение покупки"
        --> (*)
      else
        --> "Система отображает сообщение об ошибке платежа"
        --> (*)
      endif
    else
      --> "Система отображает сообщение об ошибке ввода данных"
      --> (*)
    endif
  else
    --> "Пользователь отменяет покупку"
    --> (*)
  endif
else
  --> "Пользователь продолжает просмотр продуктов"
  --> (*)
endif
@enduml