@startuml
(*) --> "Нажатие кнопки 'Регистрация'"
--> "Ввод данных"
if "Пользователь ввел данные" then
  --> [Данные введены] "Система проверяет корректность данных"
  if "Данные корректны" then
    --> [Данные корректны] "Система проверяет уникальность имени"
    if "Уникальное имя" then
      --> [Имя уникально] "Система создает учетную запись"
      --> "Завершение регистрации"
    else
      --> [Имя занято] "Система отображает сообщение об ошибке"
      --> "Вывод сообщения об ошибке"
    endif
  else
    --> [Данные не корректны] "Система отображает сообщение об ошибке"
    --> "Вывод сообщения об ошибке"
  endif
else
  --> [Данные не введены] "Система отображает сообщение об ошибке"
  --> "Вывод сообщения об ошибке"
endif
@enduml