@startuml
(*) --> "Пользователь входит в систему"

if "Пользователь авторизован" then
  --> "Система отображает профиль пользователя"

  if "Пользователь решает изменить данные" then
    --> "Система предоставляет форму для изменения данных"

    if "Пользователь вводит новые данные" then
      --> "Система проверяет корректность введенных данных"

      if "Данные корректны" then
        --> "Система сохраняет новые данные пользователя"
        --> "Система отображает подтверждение изменений"
        --> (*)
      else
        --> "Система отображает сообщение об ошибке ввода данных"
        --> (*)
      endif
    else
      --> "Пользователь отменяет изменения"
      --> (*)
    endif
  else
    --> "Пользователь продолжает просмотр профиля"
    --> (*)
  endif
else
  --> "Пользователь не авторизован"
  --> (*)
endif
@endumlё