@startuml
scale 450 width

[*] --> Начало

state Начало {
  [*] --> Ожидание
  Ожидание --> Авторизация : Вход в админ панель
}

state Авторизация {
  [*] --> Ожидание
  Ожидание --> Авторизация : Неудачная авторизация
  Авторизация --> Авторизован : Успешная авторизация
}

state Авторизован {
  [*] --> Просмотр
  Просмотр --> Изменение : Выбрана опция изменения
  Просмотр --> Удаление : Выбрана опция удаления
}

state Изменение {
  [*] --> Активный
  Активный --> Завершение : Изменение завершено
}

state Удаление {
  [*] --> Завершение : Удаление завершено
}

state Завершение {
  [*] --> Конец
}

@enduml
