@startuml
scale 450 width

[*] --> НеАвторизован

state НеАвторизован {
  [*] --> Ожидание
  Ожидание --> Авторизация : Кликнул на "Войти"
  Авторизация --> НеАвторизован : Неудачная авторизация
  Авторизация --> Авторизован : Успешная авторизация
}

state Авторизован {
  [*] --> Активный
  Активный --> СозданиеДоски : Создать доску
}

state СозданиеДоски {
  [*] --> Активный
  Активный --> СозданиеКарточки : Добавить карточку
}

state СозданиеКарточки {
  [*] --> Активный
  Активный --> СозданиеДоски : Вернуться к доске
}

@enduml