@startuml
scale 450 width

[*] --> Начало

state Начало {
  [*] --> Ожидание
  Ожидание --> Авторизация : Кликнул на "Войти"
}

state Авторизация {
  [*] --> Ожидание
  Ожидание --> Авторизация : Неудачная авторизация
  Авторизация --> Авторизован : Успешная авторизация
}

state Авторизован {
  [*] --> Покупка
  Покупка --> Завершение : Покупка завершена
}

state Завершение {
  [*] --> Конец
}

@enduml
