@startuml
scale 450 width

[*] --> НеАвторизован

state НеАвторизован {
  [*] --> Регистрация : Кликнул на "Зарегистрироваться"
  Регистрация --> Авторизован : Регистрация успешна
  Авторизован --> НеАвторизован : Выход
}

state Авторизован {
  [*] --> ДобавлениеВДоску : Создать доску
}

state ДобавлениеВДоску {
  [*] --> ДобавлениеКарточки : Добавить карточку
}

state ДобавлениеКарточки {
  [*] --> ДобавлениеВДоску : Вернуть в доску
}

@enduml