@startuml
scale 450 width

[*] --> Начало

state Начало {
  [*] --> Ожидание
  Ожидание --> Авторизация : Кликнул на "Войти"
}

state Авторизация {
  [*] --> Ожидание
  Ожидание --> Авторизация : Неудачная авторизация
  Авторизация --> Авторизован : Успешная авторизация
}

state Авторизован {
  [*] --> Изменение
  Изменение --> Завершение : Изменение завершено
}

state Завершение {
  [*] --> Конец
}

@enduml
